# Generated by Django 4.1.2 on 2022-11-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
