# Generated by Django 3.2.1 on 2022-09-08 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('kb_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('search_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JournalBatch',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Journal Batch',
                'verbose_name_plural': 'Journal Batches',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HOME', 'Home'), ('MOBILE', 'Mobile')], default='MOBILE', max_length=10)),
                ('owner', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_per', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
            options={
                'verbose_name': 'Unit Of Measure',
                'verbose_name_plural': 'Unit Of Measures',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('search_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast.contact')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorForecastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('kb_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=20, null=True)),
                ('m1_qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('m2_qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('m3_qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('m4_qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('approved', models.BooleanField()),
                ('apporved_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.item')),
                ('vendor_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Forecast Entry',
                'verbose_name_plural': 'Vendor Forecast Entries',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorForecastBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.journalbatch')),
                ('vendor_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Forecast Batch',
                'verbose_name_plural': 'Vendor Forecast Batches',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('starting_period', models.DateField()),
                ('ending_period', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entries', models.ManyToManyField(blank=True, to='forecast.VendorForecastEntry')),
                ('vendor_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Forecast',
                'verbose_name_plural': 'Vendor Forecasts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast.contact')),
                ('phones', models.ManyToManyField(blank=True, to='forecast.Phone')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MRPJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('kb_sd', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('unit_of_measure_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.item')),
                ('journal_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.journalbatch')),
                ('vendor_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.vendor')),
            ],
            options={
                'verbose_name': 'MRP Journal Line',
                'verbose_name_plural': 'MRP Journal Lines',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MRPJournalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.journalbatch')),
                ('journal_line', models.ManyToManyField(blank=True, to='forecast.MRPJournalLine')),
                ('vendor', models.ManyToManyField(blank=True, to='forecast.VendorForecastBatch')),
            ],
            options={
                'verbose_name': 'MRP Journal Batch',
                'verbose_name_plural': 'MRP Journal Batches',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit_of_measure_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecast.itemcategory'),
        ),
        migrations.AddField(
            model_name='contact',
            name='persons',
            field=models.ManyToManyField(blank=True, to='forecast.Person'),
        ),
    ]
