# Generated by Django 3.2.1 on 2022-09-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorforecast',
            name='key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorforecastentry',
            name='key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
