# Generated by Django 3.2.1 on 2022-09-09 03:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20220908_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('68e8e925-ff0b-4d67-9457-13e149dcf52c')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='item_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MRPJournalLine', to='forecast.item'),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='journal_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MRPJournalLine', to='forecast.journalbatch'),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('cf891ed5-17fc-457d-8af6-a2dcca236552')),
        ),
    ]
