# Generated by Django 3.2.1 on 2022-09-09 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_auto_20220909_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('b911a222-134a-4e50-aafe-5d197bf5c8bd')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='journal_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.journalbatch'),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9365862d-a833-4b1d-a3d2-1b9f50a8ce2c')),
        ),
    ]
