# Generated by Django 3.2.1 on 2022-09-09 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_auto_20220909_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('559776a9-76de-4311-88ad-e86b1ae83d09')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('783dd01a-080c-4c8b-8e87-cd851b7b744d')),
        ),
    ]
