# Generated by Django 3.2.1 on 2022-09-11 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_auto_20220909_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrpjournalline',
            options={'managed': True, 'ordering': ['vendor_no'], 'verbose_name': 'MRP Journal Line', 'verbose_name_plural': 'MRP Journal Lines'},
        ),
        migrations.AlterModelOptions(
            name='vendorforecast',
            options={'managed': True, 'ordering': ['vendor_no'], 'verbose_name': 'Vendor Forecast', 'verbose_name_plural': 'Vendor Forecasts'},
        ),
        migrations.AlterModelOptions(
            name='vendorforecastbatch',
            options={'managed': True, 'ordering': ['vendor_no'], 'verbose_name': 'Vendor Forecast Batch', 'verbose_name_plural': 'Vendor Forecast Batches'},
        ),
        migrations.AddField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e798e266-e2e3-474d-8403-867faf3876f1')),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('06bc18c1-1019-455a-8d84-2b1e1bb117ac')),
        ),
        migrations.AddField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2b8ad408-524c-454a-a624-54a30a7511db')),
        ),
        migrations.AddField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('97c7da25-a9a9-40b0-a11d-3c77e8bc012d')),
        ),
        migrations.AddField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('953976a4-b363-4db5-b5be-5f24c406e865')),
        ),
        migrations.AddField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('92b77916-293c-4f75-ac84-cbf936157b45')),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('8f851002-9a98-49c1-b2c0-d398dd87b79f')),
        ),
        migrations.AddField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('310a132e-d293-465c-a7c8-e5eff65085d9')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('07c1f245-03fc-4d8f-8230-233adadba658')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7ee3b374-d547-49ef-84fc-2c3dc9fcdedc')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('62c38b21-497b-4fe6-b619-fe09d5c15a52')),
        ),
        migrations.AlterField(
            model_name='vendorforecast',
            name='key',
            field=models.UUIDField(default=uuid.UUID('38c33133-ee31-4f5a-a996-937f39669f2f')),
        ),
        migrations.AlterField(
            model_name='vendorforecastentry',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fc3eb52b-d413-45f9-a052-e8e332ecfbcb')),
        ),
    ]
