# Generated by Django 3.2.1 on 2022-09-11 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_auto_20220911_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrpjournalline',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorforecast',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('3cbe27e0-2ef7-4a9e-92fb-09dfb219266b')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f0e28558-6ab3-4d06-a6b7-4e6a0abd350a')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('74942fdf-f065-42c2-9ba1-6dd3adc01050')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('76cf854a-ff90-4c67-8ba0-3a9fed40ad9f')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7cab222d-f2e6-41b4-8fa0-dac1e39181cf')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7f36c7a8-3f57-439a-99b4-190013d27910')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2656cbae-ac26-495e-8886-ee4cef4a6f41')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('22fcad20-1ba9-4f7d-84b1-8493173a0097')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('946c699a-ff7f-4b03-b216-e7b3d57a294b')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('1e467630-5ffc-4641-ad90-809312a4d37d')),
        ),
        migrations.AlterField(
            model_name='vendorforecast',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d60a3624-9d3b-43c3-8882-525e45eb53bc')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('173c305e-9148-446d-bf03-dd82c25faf79')),
        ),
        migrations.AlterField(
            model_name='vendorforecastentry',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e25b1e9d-61ef-4b76-a11c-a767f043eac5')),
        ),
    ]
