# Generated by Django 3.2.1 on 2022-09-11 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_auto_20220911_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorforecastbatch',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9104dcc4-baaf-45a5-b313-904a73004f73')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('4759761f-d164-465b-9313-d28eaeaef3ce')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('63bdca3e-b8e2-4ab8-8588-8720267b09e0')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('44e866c1-3d19-4413-b28c-76993773312f')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('af2ad14e-1fd1-4621-83d4-f6e2dbf316b7')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d55d6ec1-676c-48ad-b463-38d34d1c8399')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('31ab8fd0-7236-4666-8c84-94930006036b')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9efe66c4-5bd2-43b0-bbd1-3ddf914835f6')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('32029842-ae2b-4c8f-9e42-2d77422e774e')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('de74e3a6-659d-45c7-9958-11d1d31feeba')),
        ),
        migrations.AlterField(
            model_name='vendorforecast',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7ac9b969-8090-487f-92cc-f3e3245f3886')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('a76a491e-ad1f-4aa3-bf61-1045f6fc06d4')),
        ),
        migrations.AlterField(
            model_name='vendorforecastentry',
            name='key',
            field=models.UUIDField(default=uuid.UUID('0164137c-e479-401e-9dbc-de50f107c06c')),
        ),
    ]
