# Generated by Django 3.2.1 on 2022-10-28 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0011_auto_20220914_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5024fc19-ea38-42ef-b7dc-7a3cd3b788ad')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('99e6c4d5-19ca-4201-a71a-60923c2eb29e')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2eee1e1a-1c60-4f6e-ba1a-a5948c9f0e98')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5812d47b-825b-4d1f-80e6-ba42a158be2d')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d3cc7b6e-a1b3-47fb-8e53-a3e26b6a19a8')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('aaa1cbd8-e823-4fa7-ac4f-017586b3fae1')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('10baafdc-9f8a-4073-af22-4f228c95728d')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5814b80d-dbdb-43f7-a1a1-b8a700324840')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('4ad60bf1-96c5-4ea4-b3e9-abecbf64504a')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('51c6f226-6c46-485a-afba-3925baa02aed')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fd41cfc4-65c7-4b58-93eb-4b7ba3e725b0')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('b79167b4-4c52-428a-95c5-1a8a5c43889d')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('75b8979e-a90a-4e81-be47-37a36f8ab455')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('0ee04be2-e389-4610-9c1f-27faac4aa2a4')),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('1ab2ec16-7053-4d53-b8c4-4a29029e205e')),
        ),
    ]
