# Generated by Django 3.2.1 on 2022-10-28 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0012_auto_20221028_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('6c2e126a-3d5f-4bb3-8057-b6b228f15622')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('16447441-3fc2-4c13-aea1-a84585f17866')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7dd71708-611f-48cc-8796-215f0445b925')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('6d00ce4f-1540-406c-aa83-fe8dec07b966')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7c8bb577-cf75-43b1-a7bd-93836614fc0c')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9416738b-5c0e-44ad-ad7e-3d826736d250')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('36e024e0-ee34-48c5-902f-a8c220f83fb4')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('4f03c328-9c4b-45cf-989b-1e801c0fda5d')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('389db6b3-2211-4c4e-99c0-83481da11c22')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('bac47308-adbb-4a20-ad39-98740af6a775')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('89b4f8df-bdd6-41bd-b794-9c6e2f77b2e4')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('8028257a-b9fe-4f4f-bd30-4adb052f21f9')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('970e17a9-7197-4fa1-a7e2-3d8424234ef2')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('921a3191-426b-4bca-ae73-497bf7617188')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='vendor_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_header', to='forecast.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d36a0ecc-a032-4aa5-8305-80ca8be80542')),
        ),
    ]
