# Generated by Django 3.2.1 on 2022-10-29 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0013_auto_20221028_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('09eac991-c03a-4552-aeb8-f76b36fb3a51')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('70b434b7-acfd-4ee4-b2c4-c23f3774be71')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('a8073cf8-a538-4900-b80a-a7b2e773be01')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d47043f4-649a-4420-aa30-0196ecdc08c2')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('203c912c-9c1e-4fd0-988a-9ad1e5249814')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('8e96cb62-ff30-4c82-89d7-7a23df2088ca')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('71bcb740-1973-4d10-8a05-f1dbc6eb0c59')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('24cc16b0-6788-484c-8b19-c2d5de7f961e')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e3d33a35-6e13-41b0-8952-ea2db062e04e')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('ab006598-7e76-4a73-ba72-2b67d9eacdab')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('c384e867-b82c-4d9b-8ef1-789fe61feb9d')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('34c1ba85-b006-4bf3-bb49-c59fd9f428a6')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7e7ab71b-8708-47bb-8714-73e10e9b1c14')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('071f1886-59c0-4494-8650-fe4d84f2ba54')),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('69e160aa-8379-4dcd-9967-efd0ebef3920')),
        ),
    ]
