# Generated by Django 3.2.1 on 2022-10-29 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0014_auto_20221029_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('c26cb237-2739-482b-b5d8-e61b899c5c46')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5eb85d30-0d6a-4e78-8471-9aba535c6def')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('55cc23dd-5ed9-472e-b001-b7be231b5d2d')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('db307026-edfb-4a88-bf90-8e47105944a9')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('6be33fd9-7f67-44bf-afab-a23b87e241c1')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('dd410a5d-547a-44cf-88f6-b5da743096c3')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('b75c328a-99bc-412e-b4c6-03d4e94acd02')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('12e840fa-9ef6-4e1a-ad6e-c4ff96efa4e6')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('677c61f0-ab0a-4868-8104-d7bd10a2ae4f')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fa0f63bd-b42d-44f3-99e2-10737bd5d588')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('c0d95a58-35e1-4e69-9deb-512f3467e6cc')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('b361fd54-94e5-41ee-99f2-f3047a19d8be')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9a4595d2-3bd6-47e3-b8f3-23b9ffce64bc')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('027330b9-ad56-4ab3-abb7-c005b1ade55b')),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5f1b935d-7a0d-4a64-ad3b-3ad78f6fe149')),
        ),
    ]
