# Generated by Django 3.2.1 on 2022-10-29 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0015_auto_20221029_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorforecastline',
            name='item_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('58bd3fe7-4945-4a52-a3f2-89b542d7a087')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('ff6e607d-42dc-4111-8db9-2e29cfcad083')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('3826b440-7115-499e-87f7-784efb1a6335')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('455eae56-64c5-4fd6-9b6f-248821654dd7')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e975bac0-77e0-416c-98d2-99728c87964c')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('1eedb779-d451-49a0-8f8d-5ca27d0a9f5f')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('cb9e9f1f-1316-4618-bb93-9869f80ecac3')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('edca337b-a418-4dc7-8e17-fd2e0ca411dd')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e5efda9a-291a-430d-8c52-5e47b350ec15')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('b5936d2f-a6e2-48db-9262-c9112bb34ce3')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('73242cec-49c7-4f6d-b4b3-cffd5098f0d8')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('db4b0c8a-5833-494b-b75d-05c3603f771c')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('97f68348-b950-4f1c-8491-d3ecd857a945')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9be70711-3dc5-465e-ad8b-08fa55873061')),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d3cd910a-e572-4e05-bb39-33afa541619c')),
        ),
    ]
