# Generated by Django 4.1.2 on 2022-11-04 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0016_auto_20221030_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorforecastheader',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorforecastheader',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_forecas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7aedb410-bc34-4248-a320-b0829661f4a6')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9a5eb3dd-863e-485c-9abc-8fa948c16dfa')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('cb8aafbd-811b-4cfc-a794-b92167dc1f44')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fc8899ad-e61d-4e73-8570-bc89224b25ba')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f430fad8-0b0d-48d9-b1c2-7366fb625692')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('6c94c239-8a58-4723-b70f-06eeec183f82')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('90dc9800-a83f-40a4-9527-9c4d0287e21d')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('ec944a34-6103-4db3-9723-0bc889e016d6')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('bdd49825-9d6f-4d09-b055-c41f327a06ae')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f9fb4154-887f-488a-aa2d-ba8007a44343')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('54e5a5b4-efc8-448e-86e3-3ca672c6e1c0')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d57a09da-ca21-4ab8-b86e-2a0d2b8faf4c')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f3834886-55f3-476a-b644-ef82da1790c7')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forecas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('888ef286-1583-482b-93aa-ee87cae59d6e')),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2f96f4d5-3423-4cd6-85ef-9fc5536f3136')),
        ),
    ]
