# Generated by Django 4.1.2 on 2022-11-04 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0017_vendorforecastheader_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('11719bde-e2cd-4082-84f9-6ad4c2b1ac50')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('3f502009-8497-47df-a5c0-e5b56ea70e77')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('4de1578e-c1bc-498c-b507-c5e2d7064bf9')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d758ada2-4614-4271-9147-8fdd2de4caaf')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('31057967-d376-4b24-ad35-718112eb4676')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('c95e8084-8906-4ad1-85bd-73e28991fec2')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e2c3a399-fe15-4082-af67-3df071999aaa')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('ff13c605-b5fc-4f23-b688-a205d22b3c82')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('77ccb4a1-f029-4ed9-a171-2ddf05ff12e4')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('35186948-09f5-4416-97ae-f5ea0a9d1037')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('feb57745-9993-48db-aeff-69a0164a9f2a')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2d8ec03c-8ebb-409f-83b0-fcae76b4aeed')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('01dcb65b-9996-4bb5-98d9-09b1b10bcb51')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('2e3916ac-3533-4897-aed2-1babeaaadf43')),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('73b39f0b-7935-4c80-af43-287414e0d286')),
        ),
    ]
