# Generated by Django 4.1.2 on 2022-11-17 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0018_alter_contact_key_alter_item_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e02765d9-b9c8-46d0-8439-00fb20734e6b')),
        ),
        migrations.AlterField(
            model_name='item',
            name='key',
            field=models.UUIDField(default=uuid.UUID('b9773cad-04fe-46d7-86a8-7a36fddc2856')),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='key',
            field=models.UUIDField(default=uuid.UUID('84326be1-01b6-4767-97a4-4e89125761bd')),
        ),
        migrations.AlterField(
            model_name='journalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('98a054ad-7cd3-4645-a42b-5194e7df7ac4')),
        ),
        migrations.AlterField(
            model_name='mrpjournalbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d58b8d07-a994-4c2c-b0cf-5f3f37bf3145')),
        ),
        migrations.AlterField(
            model_name='mrpjournalline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('50392773-244f-4215-b3e4-d1f360c71763')),
        ),
        migrations.AlterField(
            model_name='person',
            name='key',
            field=models.UUIDField(default=uuid.UUID('6c7530a6-346f-4a42-a084-163b542f9e99')),
        ),
        migrations.AlterField(
            model_name='phone',
            name='key',
            field=models.UUIDField(default=uuid.UUID('c1433bfc-0764-44dc-98e4-adb10e40a5c3')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('953dcc33-b4a9-4566-8af6-f1eb3fd56f20')),
        ),
        migrations.AlterField(
            model_name='postedvendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f16c2fa3-2297-4f40-878a-d3f92d52e23f')),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='key',
            field=models.UUIDField(default=uuid.UUID('09e1823a-f559-43c0-9bce-d55af7c131f9')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='key',
            field=models.UUIDField(default=uuid.UUID('4ababf84-59d3-485d-b6dc-ff7c93f4047a')),
        ),
        migrations.AlterField(
            model_name='vendorforecastbatch',
            name='key',
            field=models.UUIDField(default=uuid.UUID('5ee936ba-d4b3-4e46-8d56-7617f3db195a')),
        ),
        migrations.AlterField(
            model_name='vendorforecastheader',
            name='key',
            field=models.UUIDField(default=uuid.UUID('80c69a2f-3fe7-4b16-a08a-a3c11470d475')),
        ),
        migrations.AlterField(
            model_name='vendorforecastline',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f042a50d-75f6-4ff7-9919-74fe0b877d42')),
        ),
    ]
